Added autocomplete feature
CodeTheChangeUBC/reBOOT pull request #327
Opened 2022-02-21 07:21 UTC by yuubd

2022-02-23 01:20 UTC, bwdmonkey requested changes

2022-02-23 01:20 UTC, bwdmonkey commented on app/templates/admin/extras/donations_change_form.html
> +  <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
we should already have jquery. please see https://github.com/CodeTheChangeUBC/reBOOT/blob/38e9c9067aacd7fd8b78c7f904282f94fc1e3c18/app/templates/admin/base_site.html#L7

2022-02-23 01:20 UTC, bwdmonkey commented on app/templates/admin/extras/donations_change_form.html
> +  <style>.ui-autocomplete { height: 200px; overflow-y: scroll; overflow-x: hidden;}</style>
please create a separate file for this css

2022-02-23 01:20 UTC, bwdmonkey commented on app/views/api_views.py
> +        return HttpResponse('', content_type="application/json")
Please either throw an error response or return empty list

2022-02-23 01:20 UTC, bwdmonkey commented on app/views/api_views.py
> +        return HttpResponse('', content_type="application/json")
Please either throw an error response or return empty list

2022-02-23 01:20 UTC, bwdmonkey commented on app/views/api_views.py
> +                deviceInfo = device.dtype.device_type + \
please use f-string for readability. https://www.geeksforgeeks.org/formatted-string-literals-f-strings-python/

2022-02-23 01:20 UTC, bwdmonkey commented on app/views/api_views.py
> +        return HttpResponse('', content_type="application/json")
Also please return as JsonResponse or HttpResponse with error

2022-02-23 01:20 UTC, bwdmonkey commented on app/views/api_views.py
> +        return HttpResponse('', content_type="application/json")
Also please return as JsonResponse or HttpResponse with error

2022-02-23 01:20 UTC, bwdmonkey commented on app/templates/admin/extras/donations_change_form.html
> +      let matches = $.map(source, (item) => {
`const`

2022-02-23 01:20 UTC, bwdmonkey commented on app/templates/admin/extras/donations_change_form.html
> +      const input = request.term;
Where does `term` come?

2022-02-23 01:20 UTC, bwdmonkey commented on app/templates/admin/extras/donations_change_form.html
> +      let matches = $.map(source, (item) => {
lets also use the native map over `$.map` when possible

2022-02-26 04:34 UTC, yuubd commented on app/templates/admin/extras/donations_change_form.html
> +      const input = request.term;
Is the input in the search bar.

2022-02-28 03:26 UTC, bwdmonkey approved these changes
minor comments. LGTM. please test and merge when ready

2022-02-28 03:26 UTC, bwdmonkey commented on app/templates/admin/extras/donations_change_form.html
> +  <link rel="stylesheet" href="//code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">
please move this to the extrastyle block

2022-02-28 03:26 UTC, bwdmonkey commented on app/templates/admin/extras/donations_change_form.html
> +        sortedDonorNames = res.donorNames.sort();
please mark as const to avoid this being declared as global var

2022-02-28 03:26 UTC, bwdmonkey commented on app/views/api_views.py
> +        donor_names = [donor.donor_name for donor in Donor.objects.all()]
see https://docs.djangoproject.com/en/4.0/ref/models/querysets/#values-list or https://docs.djangoproject.com/en/4.0/ref/models/querysets/#values for more optimized sql fetch and avoid unnecessary slower python enumeration

2022-02-28 03:26 UTC, bwdmonkey commented on app/views/api_views.py
> +        return JsonResponse(e)
you will prob want to return with a status=500 or something as this will be resolved as 200 in ajax resolver if not

2022-02-28 03:26 UTC, bwdmonkey commented on app/views/api_views.py
> +        return JsonResponse(e)
same here

2022-03-02 03:17 UTC, merged